commonLabels:
  release: production
  author: jacksonrakena
namespace: production

resources:
  # Nginx
  - nginx/

  # Certificates
  - secrets/rakena-cert.yaml

  # Secrets
  - secrets/gh-container-registry.yaml
  - secrets/galahad-secret.yaml
  - secrets/gradekeeper-config.yaml
  - secrets/jacksonbot-config.yaml

  # App stack
  - ../stack

  # Ingresses
  - ingress.yml
