apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: identity
  # Template for each Galahad Pod (there is really only one)
  template:
    metadata:
      labels:
        app: identity
    spec:
      volumes:
        - name: identity-config-mount
          configMap:
            name: identity-config

      containers:
        - name: zitadel
          image: ghcr.io/zitadel/zitadel:latest
          ports:
            - containerPort: 8080
          args:
            - start-from-init
            - --config
            - /zitadel.yaml
            - --masterkeyFromEnv
          envFrom:
            - configMapRef:
                name: identity-env
          volumeMounts:
            - name: identity-config-mount
              mountPath: /zitadel.yaml
              subPath: zitadel.yaml
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: identity
  name: identity
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: identity
  type: ClusterIP
