apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamapps-server
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: streamapps-server
  template:
    metadata:
      labels:
        app: streamapps-server
    spec:
      volumes:
        - name: streamapps-config-mount
          configMap:
            name: streamapps-config
      containers:
        - name: server
          image: ghcr.io/jacksonrakena/streamapps-server:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: streamapps-config-mount
              mountPath: /app/secrets.json
              subPath: secrets.json
      imagePullSecrets:
        - name: gh-container-registry
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: streamapps-server
  name: streamapps-server
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: streamapps-server
  type: ClusterIP
